# Setup
title: Yulie's Blog
tagline: "A place to record thoughts and knowledges"
description: ""
url:
baseurl: ""
paginate: 5
permalink: pretty
excerpt_separator: <!--more-->

collections:
  projects:
    output: true
  etc:
    output: true

# About/contact
author:
  name: Yulie Jung
  url:
  email: jungyulie@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id:
